### ISSUE TITLE
Readme with example?

### ISSUE THREAD

**Issue by ignatandrei** [Yeah69/MrMeeseeks.SourceGeneratorUtility#1]
I do maintain a list of RSCG at https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG

I did find your - but I cannot understand the usage

Could you put into readme.md?

**Comment by Yeah69** [comment]
Hello,

first of all, I think your page listing Roslyn source code generator (RSCG) projects is very nice. I've spotted some interesting projects that I didn't know of yet. I think I'll return to it in future. ;)

That said, I'm not sure whether this project is a good fit. This repository in particular doesn't host an actual RSCG (you won't finde an `ISourceGenerator` or `IIncrementalSourceGenerator` implementation here). This is just meant as a library with useful functions meant for other RSCG projects. Because I have several RSCG projects now, I wanted to keep it "DRY" (as in "Don't Repeat Yourself") and create a library with the shared functionalities.

This library isn't polished at all. It just contains the functions that I needed in my RSCG projects so far. If it is useful for someone else, it's okay.

However, I have some other RSCG projects that might be of interest for your page with the list:
- [MrMeeseeks.DIE](https://github.com/Yeah69/MrMeeseeks.DIE) A Dependency Injection container generator. It also has a dedicated [documentation homepage](https://die.mrmeeseeks.dev/) and recently I started to build a [DI container feature comparison page](https://yeah69.github.io/ContainerFeatureSampleComparison/).
- [MrMeeseeks.Visitor](https://github.com/Yeah69/MrMeeseeks.Visitor) A generator for the boilerplate code of the Visitor pattern from the Gang of Four.
- [MrMeeseeks.ResXToViewModelGenerator](https://github.com/Yeah69/MrMeeseeks.ResXToViewModelGenerator) A generator which generates ViewModel classes based on ResX localization files (relevant for WPF-like UI apps that use the Model-View-ViewModel MVVM pattern and ResX files for localization)
- [MrMeeseeks.StaticDelegateGenerator](https://github.com/Yeah69/MrMeeseeks.StaticDelegateGenerator) A generator for the - what I call - "Static Delegate" pattern (it's described in more detail in the ReadMe)

I would feel honored if any of these RSCG projects make it to your list. :) These also have pretty accurate ReadMe's (with the exception of MrMeeseeks.ResXToViewModelGenerator).

Last thing that I want to mention. Do you know of this repository: [csharp-source-generators](https://github.com/amis92/csharp-source-generators)? It seems that its purpose (i.e. to list RSCG projects) is similar to your list. Maybe it can be a source of inspirations for your list.

**Comment by ignatandrei** [comment]
Thanks for your comment. 

Yes, I know the repo [csharp-source-generators](https://github.com/amis92/csharp-source-generators) . I am looking sometimes

And yes, I know the other yours RSCG. Unfortunately, my RSCG list is very opinionated. I do not want to test something that is on ISourceGenerator , but only on IIncrementalGenerator ( to justify partially, is because of how dotnet build / VS behaves ) 
If you are upgrading those, please let me know .

Thanks again!
